### ISSUE TITLE
Named imports with `as` aren't sure where to go

### ISSUE THREAD

**Issue by scottrepreneur** [lydell/eslint-plugin-simple-import-sort#139]
I'm having some trouble when using this with an overridden naming convention.

```js
import {
  Input as ChakraInput,
  InputProps as ChakraInputProps,
  FormControl,
  FormLabel,
  // tries to resort down here, then back to the top cause of the C-name
  InputGroup,
  InputRightElement,
} from '@chakra-ui/react';
```

Importing like this causes the plugin/rule to run and (probably) correctly sort, but the rule is also still firing an error so it tries to additionally run every time. I'm fairly indifferent to supporting sorting by the true import or by the `as` name, but would be great to resolve the error case.

**Comment by lydell** [comment]
Hi! Imported items are sorted on the word to the left of _as:_

```
  InputProps as ChakraInputProps,
  ^^^^^^^^^^
  sorted on
```

eslint-plugin-simple-import-sort tries to stay “stable“ when it sorts – making small changes shouldn’t make lines jump around. So deciding to add an `as` shouldn’t make that line move. Same for `type`.

The code you posted results in this after running `eslint --fix` once:

```js
import {
  FormControl,
  FormLabel,
  Input as ChakraInput,
  // tries to resort down here, then back to the top cause of the C-name
  InputGroup,
  InputProps as ChakraInputProps,
  InputRightElement,
} from '@chakra-ui/react';
```

…and then stays that way.

Can you help me understand what your issue is?

**Comment by scottrepreneur** [comment]
Ah, I was hitting a conflict with VSCode's setting here.
`"source.organizeImports": true`
Thanks for the quick response.
