### ISSUE TITLE
Import in group despite not being matched by regex expression

### ISSUE THREAD

**Issue by simPod** [lydell/eslint-plugin-simple-import-sort#160]
Why are my imports sorted like this

```tsx
import '@app/client/Components/SwaggerUI/swagger-ui.scss';
import React from 'react';
import SwaggerUI from 'swagger-ui-react';

import { apiUri } from '@app/client/API/endpoints';
```

with config 
```
            groups: [
              ['^(?!(@app|\\.)/).+$'],
              ['^'],
```

I'd expect `@app/client/Components/SwaggerUI/swagger-ui.scss` to be in the second group since the first group regex does not match it.

https://regex101.com/r/4lfQvP/1

I'd expect

```tsx
import React from 'react';
import SwaggerUI from 'swagger-ui-react';

import { apiUri } from '@app/client/API/endpoints';
import '@app/client/Components/SwaggerUI/swagger-ui.scss';
```

**Comment by lydell** [comment]
`import '@app/client/Components/SwaggerUI/swagger-ui.scss';` is considered a “side effect” import, since it does not expose any values to the file – it’s just imported for its side effects. Some people use this to set up polyfills. Then it’s important that those imports stay at the top, so that they run before everything else. For this reason, side effect imports have a `\u0000` character prepended at the start of their `from` string when grouping. That’s a bit of an ugly solution, but it makes sure that that they don’t match other groups (since typically people use regexes that check for a certain prefix), and it’s then possible to use `"^\\u0000"` to make a group for them (like the default settings do).

So in practice, this is the string used when grouping: `'\u0000@app/client/Components/SwaggerUI/swagger-ui.scss'`. It matches your first regex so it ends up there.

**Comment by simPod** [comment]
Aight, I understand the mechanism now, thanks!
