### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by maranomynet** [lydell/eslint-plugin-simple-import-sort#163]
Any chance of an upgrade with support for newer versions of ESLint?

**Comment by maranomynet** [comment]
I'm exploring converting my eslint (v8.57) config to use the new "flat config" (like so):

```js
// @ts-check
import simpleImportSort from 'eslint-plubin-import-sort';

/** @type {Array<import('eslint').Linter.FlatConfig>} */
export default [
  {
    plugins: {
      'simple-import-sort': simpleIimportSort,
    },
    rules: {
      'simple-import-sort/exports': 'warn',
      // ...other rules
    }
  }
]
```

…and I get this TS error:

<img width="497" alt="image" src="https://github.com/lydell/eslint-plugin-simple-import-sort/assets/86827/8ba8594f-3810-4533-a5d8-2d0b0578b9c3">

**Comment by maranomynet** [comment]
Does this make sense, or am I making some silly mistake?

**Comment by lydell** [comment]
Thanks! I was wondering, because I already updated the plugin for ESLint 9 in https://github.com/lydell/eslint-plugin-simple-import-sort/pull/155. (To be extra clear, the plugin already worked with ESLint 9 and flat config, that PR just added an extra `meta` property and docs.)

The only thing I’m missing for “best in class flat config support” is types (see https://github.com/eslint/eslint/issues/18093). I’ve only tested with plain JS, never TypeScript. I haven’t learned the best way to type an ESLint plugin yet.

In the code you posted there are a couple of errors:

1. You import `eslint-plubin-import-sort`, but the actual name is `eslint-plugin-simple-import-sort`.
2. You try to reference `simpleIimportSort` which is not defined.

However, the type errors in the screenshot seem to indicate other errors. I can’t tell from the information you provided what’s going on. I would have expected errors about `eslint-plugin-simple-import-sort` not providing any types if anything.

Either way, until I have added types to the package (or someone else has contributed them), you should be able to `@ts-ignore` (or similar) TypeScript errors and it should still work (as long as you’ve done everything correctly – see the README for examples).

**Comment by maranomynet** [comment]
Yeah, so much for my ability to rapidly type in rough code
examples.😅.

Great to know that I can just ignore the errors. Thanks!

**Comment by maranomynet** [comment]
I guess that as a quick and dirty solution you could do something like asserting that your exported rules are of type `Linter.FlatConfig['plugins']['rules']` etc. ...without actually digging further into what the actual differernce is

**Comment by lydell** [comment]
Version 12.1.0 has just been released with TypeScript types.
