### ISSUE TITLE
Is there a way to sort default imports aboved named imports?

### ISSUE THREAD

**Issue by NullVoxPopuli** [lydell/eslint-plugin-simple-import-sort#52]
in a group, I have:
```js
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { inject as service } from '@ember/service';
```

all of those are in my custom "framework" group.

but, when apply the auto-fix, `@glimmer/component` moves to the bottom, because g comes after e.

Is there a way to keep it at the top, because it's a default import?

For example, previously, I had:
```js
  'sort-imports-es6-autofix/sort-imports-es6': [2, {
    'ignoreCase': false,
    'ignoreMemberSort': false,
    'memberSyntaxSortOrder': ['single', 'all', 'multiple', 'none'],
  }],
```
which looks like:
```js
import single from 'a';
import * from 'b';
import { foo, bar } from 'c';
import from 'd';
```

i'd like to maintain that to reduce impact to the (very large) codebase (and people's workflows)

**Comment by lydell** [comment]
Hi! There’s no way to do this, because it has roughly the same problems as mentioned here: https://github.com/lydell/eslint-plugin-simple-import-sort#why-sort-on-from

In other words, if you change from `import Def from "a"` to `import { somethingElse } from "a"` the import will jump around, which is bad for diffing and might cause merge conflicts.

It also begs the question what should happen if an import has both a default import _and_ specifiers: `import Def, { somethingElse } from "a"` and how `import * as X from "a"` comes into play, which is nice not having to think about.

So I’m not willing to add this. But thanks for using the plugin and raising the issue!
