### ISSUE TITLE
Allow sorting side-effect imports?

### ISSUE THREAD

**Issue by rabelloo** [lydell/eslint-plugin-simple-import-sort#65]
## The goal
To align with VSCode's "Organize Imports" and the old TSLint sort order by using ESLint and this plugins' options.
```ts
rules: {
  imports: ["error", { groups: /* something that outputs example below */ }]
}
```

## Example output
```ts
import '@scoped/package/a.css';
import { a } from '@scoped/package/b';
import '@scoped/package/c.css';
import 'package/d.css';
import { e } from 'package/e';
import 'package/f.css';
import './relative/path/g';
import { h } from './relative/path/h';
import './relative/path/i';
```

Essentially the only thing that matters for sorting each line is the import path.

## The issue
Side-effect imports are sorted separately and can't be customised
https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/src/shared.js#L709

```ts
// If both items are side effect imports, keep their original order.
itemA.isSideEffectImport && itemB.isSideEffectImport
  ? itemA.index - itemB.index
  : // If one of the items is a side effect import, move it first.
  itemA.isSideEffectImport
  ? -1
  : itemB.isSideEffectImport
  ? 1
  : // ... rest of compare function
```

There is currently no way to configure groups so that they output like the example above.

## Proposed solution
To remove the special resolution of `isSideEffectImport` and instead rely more on `groups`.

Removing lines 709 to 716 makes it possible to achieve the goal above with the following configuration:

```ts
"groups": [
  // \\0? makes named vs unnamed imports irrelevant
  [
    "^\\0?[^\\.]", // non-relative paths (packages)
    "^\\0?\\." // relative paths
  ]
]
```

Default behaviour will stay exactly the same.

Explicit configuration is still possible with:

```ts
"groups": [
  // side effect imports
  ["^\\0"],
  // ... all the rest
]
```

**Comment by lydell** [comment]
Hi! Thanks for the detailed issue!

There’s a reason for the current behavior. Within a group, the plugin never changes the order of side effect imports, so that it doesn’t change the order of the side effects. The easiest way of doing that is to sort all the side effect imports first, in their original order.

With your proposal, this:

```js
import "./polyfills"
import "./init"
```

would become:

```js
import "./init"
import "./polyfills"
```

right? That breaks if `"./init"` depends on polyfills already being in place.

One thing I thought of was to make the sorting more complicated and _try_ to sort side effect imports alphabetically like all other imports as much as possible, but still making sure that all the side effect imports within the group are in the original order. However, I’m not sure that would be a good solution for you. You would have to manually be on the lookout for side effect imports not appearing where you want, and manually move them into place (since the plugin does not dare changing their order).

**Comment by rabelloo** [comment]
To be honest I never manage import statements manually, I just let VSCode organize them for me on save.
However having an ESLint rule would be ideal so that other team members aren't required to use VSCode.

I totally understand why that code is needed, even though we don't have any file that introduces side-effects.
Frankly I think that's more correct than what VSCode does but then again side-effects are a frowned upon pattern.

If you agree that the only requirement is keeping side-effect imports in the order they were specified in, this could possibly work and not introduce any additional complexity:

```ts
// If both items are side effect imports, keep their original order.
itemA.isSideEffectImport && itemB.isSideEffectImport
  ? itemA.index - itemB.index
  : // ... rest of compare
```

Which means deleting lines 711 through 715.

That achieves both goals, mine and yours, I believe.

**Comment by lydell** [comment]
Hmm, yes, that might work, good idea! I’ll play around with that.

Be warned though that being compatible with VSCode’s “organize” imports is not a goal, so you might bump into new issues at any time in the future.

**Comment by rabelloo** [comment]
Fantastic, thanks!

No worries, as long as the tool is flexible enough for me to configure it to be compatible I think I'm good.

**Comment by lydell** [comment]
Btw, have you tried any of these?

- https://www.npmjs.com/package/prettier-plugin-organize-imports
- https://www.npmjs.com/package/organize-imports-cli

They might be closer to what you need than this plugin.

**Comment by rabelloo** [comment]
Ideally it'd be a lint rule, so I skipped `prettier-plugin-organize-imports` - Prettier's philosophy is not altering AST.

`organize-imports-cli` looks okay though, we do use lint-staged.
It's not nearly as broadly used as yours, but I'll give it a try, thanks!

Still if you're willing to change those lines this plugin would still suit us quite well.

**Comment by lydell** [comment]
Deleting lines 711 through 715 didn’t work – side effect imports could still swap order then.

But it turns out the current code doesn’t prevent order swapping in all cases either, which is a bug.

So it looks like implementing this issue fixes a bug.

I have some proof-of-concept code that sorts as much as possible while still guaranteeing the order of the side effect imports is the same. I’ll play around with it some more and then try to release a new version when I get the time.

**Comment by rabelloo** [comment]
Interesting that it doesn't work, it should follow the configured order based on the regexes 🤷🏻‍♂️

Sounds good, two birds with one stone.

Thanks a bunch for your responsiveness, I really appreciate it.

**Comment by lydell** [comment]
> Interesting that it doesn't work, it should follow the configured order based on the regexes 🤷🏻‍♂️

This is about a _single group_ (i.e. where all items match the same regex) and that group containing both side effect imports and other imports. (By default there’s no mixed group, but it’s possible to configure one.)

**Comment by lydell** [comment]
I made some progress on this today. I thought I had the perfect algorithm, but when writing tests I realized that the problem is much trickier than I thought.

Keeping the current behavior and fixing the bug would be easy.

Supporting your use case is harder, but might be doable. Back to the drawing board.

**Comment by rabelloo** [comment]
Appreciate your hard work here.
If it helps make a decision, we have been using the Prettier plugin for a while and it has been sufficient.
If you find the use case too hard to support, I'd understand.

**Comment by lydell** [comment]
I’ve come up with one solution … that _kind of_ works. The idea is to let every side effect import _keep its index in the group,_ and only sort the imports _between_ the side effect imports. This allows VSCode’s “organize imports” feature to decide the final order. But I don’t think it’ll help you. The rule will kind of stop sorting your imports if you have lots of side effect imports (CSS imports), instead of enforcing that “organize imports” has been run.

I also realized that there seems to be no bug present with the current “move side effect imports to the top” logic. It was just test code was wrong.

So the more I think about this – it sounds like what you need is an `sortSideEffectImports: "I know what I'm doing" | "Keep their order"` option. But I’m not sure if that’s a good option to have. Especially if you don’t end up using it anyway because you use the Prettier plugin instead.

**Comment by rabelloo** [comment]
Yea that doesn't work for me, as VSCode's "organize imports" can't be triggered by a script, we need another tool to do it.
We need it to work consistently in the CI as well.

If you think this feature is not desirable in your tool, I get it, we can use the Prettier plugin.
Ideally it'd be an ESLint rule but 🤷🏻

I'd argue allowing explicit configuration of the ordering would be beneficial for all, but I can see how that's hard to implement and test.

**Comment by haxxxton** [comment]
apologies for reviving an older ticket, but i would definitely appreciate being able to have a little more control over the different types of side-effect imports. specifically i would like to place packaged side-effects (ie ones i import directly from node_modules vs the ones i import locally). For example, i would love to be able to:

```js
import 'intl';
import 'intl/locale-data/jsonp/en';
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import memoize from 'memoize-one';
import { momentObj } from 'react-moment-proptypes';
import { NakedDatePicker } from 'motif';

import { VIEW } from '../../constants';
import styles from './styles.scss';
import './iframeSandbox';
```

mostly because otherwise i have to disable the `eslintimport/first` rule if either the packaged side effects come to the bottom, or if the relative side effects come to the top

**Comment by lydell** [comment]
What is `eslintimport/first`?

**Comment by haxxxton** [comment]
@lydell apologies thats a typo it should read `import/first` comes as part of the `eslint-plugin-import` which is a requirement for `eslint-config-airbnb`

**Comment by haxxxton** [comment]
So i have simple-import-sort/imports set up like so:

```js
'simple-import-sort/imports': [
  'error',
  {
    groups: [
      [
        // Packages. `react`\`react-dom` packages come first.
        '^react(-dom)?$',
        '^prop-types',
        // Internal packages come last.
        '^\\w',
        '^@'
      ],
      [
        // aliases first
        '^[~]',
        '^fixtures',
        // Parent imports. Put `..` last.
        '^\\.\\.(?!/?$)',
        '^\\.\\./?$',
        // Other relative imports. Put same-folder imports and `.` last.
        '^\\./(?=.*/)(?!/?$)',
        '^\\.(?!/?$)',
        '^\\./?$',
        // With Side effect imports
        '^\\u0000'
      ]
    ]
  }
],
```

Whats that's causing to happen is to drag my non-relative _and_ package side-effect imports to the bottom of the imports (like so)
```js
import $ from 'jquery';

import { EVENTS } from '../../../constants';
import 'viewerjs/dist/viewer.css';
import '../plugin';
```

where ideally id be able to leave the package side-effect imports at the top, and the relatives at the bottom like this:
```js
import 'viewerjs/dist/viewer.css';
import $ from 'jquery';

import { EVENTS } from '../../../constants';
import '../plugin';
```

**Comment by lydell** [comment]
Yes, I understood that, but not what this has to do with `import/first`?

**Comment by haxxxton** [comment]
@lydell, sorry im doing a terrible job of explaining. Hopefully pictures will help

With the config listed above, when i use it on a file that contains both non-relative and relative side-effect imports 
```js
import $ from 'jquery';

import { EVENTS } from './util';
import 'viewerjs/dist/viewer.css'; // <-- needs to be higher for dependency purposes, and it makes import/first complain
import './plugin';
```
![image](https://user-images.githubusercontent.com/743105/129214298-58aaadd1-711a-4bde-8328-a78be62c8844.png)

If i flip my config so that side effects are at the very top then this happens
```js
import 'viewerjs/dist/viewer.css';
import './plugin'; // <-- needs to be lower for dependency purposes, and it makes import/first complain
import $ from 'jquery';

import { EVENTS } from './util';
```
<img width="951" alt="Screen Shot 2021-08-13 at 12 28 42 am" src="https://user-images.githubusercontent.com/743105/129214935-758d2a63-8199-49b4-ac5a-76b5daaa534a.png">

**Comment by haxxxton** [comment]
Thats been the solution ive had to use at the moment, and it has eslint passing now :) I will have to see if i can get a replicable example together for the dependency issue, but its likely going to be a pain. Essentially there are some files in my project that have both non-relative and relative side effects imports. before adding the sorting plugin we made sure that the non-relative imports were always at the top of the file, and relatives as the last in the import block. im unsure what is responsible for trying to calculate circular dependency avoidance, hoisting etc, but for some files, moving these imports either all to the bottom or all to the top is breaking my build

**Comment by lydell** [comment]
Ouch! Sounds like you have some very annoying side effect stuff going on there! I think it would improve your code base to sort that out (pun not intended), but I understand it can be hard. Until then, having automatically sorted imports sounds very dangerous – I wouldn’t do that myself.

**Comment by lydell** [comment]
But hey, I just realized: Can’t you already do what you want? Use a regex like `'^\\u0000[^.]'` to match side effect imports from packages, and `'^\\u0000\\.'` to match local ones (the regexes might need tweaking)?

**Comment by haxxxton** [comment]
@lydell KING! thank you sir, that final set of regex's was exactly what i was looking for! I really need to up my regex-fu! thank you sir <3

**Comment by lydell** [comment]
I’ve made up my mind. Automatically sorting side effect imports is not safe, and I don’t want an unsafe option. I’m updating the readme: #93
