### ISSUE TITLE
Add a shareable config

### ISSUE THREAD

**Issue by aaronadamsCA** [lydell/eslint-plugin-simple-import-sort#66]
If you were to export a shareable config, you could make usage require just one line in `.eslintrc`, for example:

```json
{
  "extends": ["simple-import-sort/recommended"]
}
```

This would also allow you to adjust the recommended config to enable additional recommended rules with future releases.

Many packages use this approach, a good example is here: https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/index.js

```js
export const configs = {
  recommended: {
    plugins: ['react-hooks'],
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
};
```

Docs are here: https://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs

Thanks, very helpful plugin!

**Comment by lydell** [comment]
Hi!

What would you expect to be in the recommended config?

See also the previous related discussion: https://github.com/lydell/eslint-plugin-simple-import-sort/pull/14

**Comment by aaronadamsCA** [comment]
Sorry for the overlapping ticket, I did search for one!

I was thinking something very simple that matches the current docs:

```js
export const configs = {
  recommended: {
    plugins: ["simple-import-sort"],
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      "sort-imports": "off",
      "import/order": "off"
    },
  },
};
```

This should cover the first three blocks under [Usage](https://github.com/lydell/eslint-plugin-simple-import-sort#usage). I figure you can't really include the rest in a shareable config, since you don't know if they've installed `eslint-plugin-import` or which files are CommonJS.

**Comment by lydell** [comment]
Thanks!

I’ve been thinking about restructuring the docs a little. Personally, I never turn off `sort-imports` and `import/order`, because I don’t even turn them on in the first place. I also never set the `simple-import-sort` rules to `error` – I set them to `warning` during development and to `error` in CI (this way I get yellow underlines in VSCode instead of red).

So all that you _need_ to do is adding `"simple-import-sort"` to `plugins` and enable the rules you want at the places you want. Then, you just need to make sure there are no conflicting rules. If there are, remove or disable them.

Btw, `"import/order": "off"` fails if that plugin isn’t installed:

> Definition for rule 'import/order' was not found

So then the recommended config just enables the two rules from this package and disables one. Does that gain anything? I’m worried it just makes things unclear. Now people have to look up what `simple-import-sort/recommended` means.

**Comment by aaronadamsCA** [comment]
I think you can `!!require.resolve('eslint-plugin-import')` to check if another plugin is installed.

I use 7 fairly common ESLint plugins/configs and this is the only one that doesn't ship a shareable config. It became more noticeable when I upgraded and needed to change my rules; if I'd been extending a config you shipped, you would have been able to add the new export rules to that config with the major release.

If you control the standard config most people use, I just figure it's easier for people to install it and use it and maintain it. You maybe get fewer issues filed too. It's not a huge thing either way, just a nice convenience!

**Comment by lydell** [comment]
I’ve decided not to do this.
