### ISSUE TITLE
Separate import and import type

### ISSUE THREAD

**Issue by DecliningLotus** [lydell/eslint-plugin-simple-import-sort#84]
With the new `import type` syntax in Typescript, I feel it would be better for that to be separated than treated the same as any other import currently.

For example, there should be a separation between the two with an empty line, whilst the current setup autofixes both of them together.
![2021-08-31_02-26](https://user-images.githubusercontent.com/38220115/131418405-3cb4d422-1235-4a8b-9851-7bf21811b83f.png)

**Comment by lydell** [comment]
Hi! You can do this with [Custom grouping](https://github.com/lydell/eslint-plugin-simple-import-sort/tree/1f753fb3e5b8eadf6cf9fdda8790d01dd9eade26#custom-grouping):

> Type imports have `\u0000` appended to their `from` string (ends with `\u0000`). You can match them with `"\\u0000$"` – but you probably need more than that to avoid them also being matched by other groups.

**Comment by DecliningLotus** [comment]
Thank you! Would you believe this suggestion is suitable for default behaviour, however?

**Comment by lydell** [comment]
There used to be a separate group for type imports: https://github.com/lydell/eslint-plugin-simple-import-sort/blob/1f753fb3e5b8eadf6cf9fdda8790d01dd9eade26/CHANGELOG.md#version-200-2018-11-30

> - Changed: Flow type imports are no longer put in their own group at the top. Type imports from npm packages are grouped among regular npm imports, relative type imports are group among regular relative imports, and so on. The reason for this change is the same as for sorting on `from` – to avoid import “jumps” when they change. Previously, changing `import type { User } from "./user"` into `import { type User, getUser } from "./user"` caused the line to jump from the top of the file (the type imports group) to further down (the relative imports group). Now it stays in the relative imports group in both cases.

That was for Flow, though, not TypeScript (Flow has had type imports for much longer, and slightly differently).

Since then I’ve moved to TypeScript. I’ve tried type imports in TypeScript a bit. At first that did cause a lot of `import`➡️`import type` flipping (and back), but then I felt that `import type` was useless so I basically stopped using it.

So my current stance is:

- There might be an argument for not having a separate group (less unnecessary diff).
- I like the current defaults are pretty simple.
- It feels like changing the defaults here would lead to a bit of bike shedding, and since I personally don’t really use type imports that wouldn’t be very interesting.

What do you think?

**Comment by DecliningLotus** [comment]
In the end, I think it's subject to developer preference. I feel like the idea of differentiating `import type` from `import` is a logical conclusion rather than treating them identically and I'm sure some developers would like that. I personally like to use `import type` since it helps organize my types away from the actual functional imports - which is far nicer than getting my types lost in the mix of imports. 

What if we have it set as an opt-in rule? 
```
{
  "rules": {
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    // New rule
    "simple-import-sort/imports-type": "error"
  }
}
```

**Comment by lydell** [comment]
What would the new rule do?

**Comment by DecliningLotus** [comment]
The behaviour to treat import type differently and split them up. 

The base rules aren't changed. But you could opt-in with an additional rule to adjust how import type is handled on autofix.

Unless I'm misunderstanding how ESLint rules behave?

**Comment by lydell** [comment]
To me it sounds like the rules would conflict with each other, autofixing the imports in different directions in an endless cycle.

What’s wrong with the configuration we have?

**Comment by lydell** [comment]
My conclusion here is:

- The defaults won’t change soon.
- But feel free to open an issue about the defaults if you like, which could stay open for a long time to collect feedback from others.
